### ISSUE TITLE
How to access instance memory from imported go function

### ISSUE THREAD

**Issue by noot** [wasmerio/go-ext-wasm#47]
### Summary
I am trying to access the memory of the wasm instance from an imported Go function, but I can't find info on this.  Here's my imported Go func:

```
//export ext_print_utf8
func ext_print_utf8(context unsafe.Pointer, offset int32, size int32) {
	// want to print out some string from inside the instance memory at [offset:offset+size]
}


```

**Comment by Hywan** [comment]
You have to use [`IntoInstanceContext`](https://godoc.org/github.com/wasmerio/go-ext-wasm/wasmer#IntoInstanceContext). Unfortunately, the existing example cannot be loaded in godoc because it depends on cgo, but you can view it in Github:

https://github.com/wasmerio/go-ext-wasm/blob/722faa9f1b902d404e87c40ea2bb6bdd5e228a51/wasmer/test/imports.go#L134-L140

Does it help?

**Comment by noot** [comment]
Yes that helps! Thanks so much.

**Comment by Hywan** [comment]
❤️

**Comment by Hywan** [comment]
Note that it is also possible to use an “instance context data”, see:

https://github.com/wasmerio/go-ext-wasm/blob/722faa9f1b902d404e87c40ea2bb6bdd5e228a51/wasmer/test/imports.go#L162-L194

**Comment by noot** [comment]
Awesome, that was actually the next question I was going to ask. Thanks so much for your help :)
