### ISSUE TITLE
Using wasmer from goroutines

### ISSUE THREAD

**Issue by maxim-ge** [wasmerio/go-ext-wasm#84]
### Summary

What is the safe way to use wasmer from multiple goroutines?

### Additional details

If `instance` (result of `wasm.NewInstance`)  is used by only one goroutine at any time -  is it enough? The potential problem is that one goroutine might be executed by few threads.

**Comment by Hywan** [comment]
Since https://github.com/wasmerio/wasmer/pull/807, I would say it is safe to use `Instance` in multiple threads yes, but I'm double-checking with some other members of the team.

**Comment by Hywan** [comment]
Some precisions:

* It is safe to use an instance from multiple threads (since `Instance` implements [`Send`](https://doc.rust-lang.org/std/marker/trait.Send.html) in the runtime, written in Rust),
* It isn't safe to re-enter the `Instance` from a Go function called as an imported function of the same instance (since `Instance` doesn't implement [`Sync`](https://doc.rust-lang.org/std/marker/trait.Sync.html) in the runtime).

**Comment by Hywan** [comment]
https://golang.org/pkg/runtime/#LockOSThread can be useful for reentrance.

**Comment by maxim-ge** [comment]
Can I  re-conclude a bit?

1. It is safe to use `Instance` from goroutines provided goroutines  are synced (only one goroutine invokes `Instance`s method, but Instance can be safely re-used by another goroutine)
2. It is not safe to re-enter Instance from imported functions even provided (1) is satisfied

Correct?

**Comment by Hywan** [comment]
`Instance` can be used by any goroutines at a time, but cannot be sent to another goroutine.

**Comment by maxim-ge** [comment]
Ok, https://golang.org/pkg/runtime/#LockOSThread  does the job, thank you very much!

**Comment by Hywan** [comment]
https://github.com/wasmerio/go-ext-wasm/issues/84#issuecomment-554976575 isn't true. I didn't know that goroutines can run on a same thread or can be moved to another thread.
