### ISSUE TITLE
Is go-wasmer can handle wasm file build from golang codes

### ISSUE THREAD

**Issue by louisliu2048** [wasmerio/go-ext-wasm#87]
### Summary
Thank u for your wonderful work. I ran all the example, and it works well on my mac. But when I intend to replace the simple.wam with my wasm, some thing panic happend. 

### Additional details
Here is my go file:
![image](https://user-images.githubusercontent.com/35095310/69324522-98add680-0c83-11ea-989e-cedfef6903f0.png)
And I use this command to build my wasm File:
` GOARCH=wasm GOOS=js go build -o hello.wasm hello.go`
Then I replace the file and function call by your example code:
![image](https://user-images.githubusercontent.com/35095310/69324707-e591ad00-0c83-11ea-83ba-d226c9e818c1.png)
But when I try to run 'my example'，panic happend!
![image](https://user-images.githubusercontent.com/35095310/69325302-e7a83b80-0c84-11ea-9538-7ed053f62d20.png)

Any help for me?

**Comment by waynr** [comment]
@louisliu2048 one problem here is that you are following bogus examples that ignore errors; if you don't ignore error values returned from `wasmer'` functions then you won't ever reach the panic, ie:

```
instance, err := wasm.NewInstance(bytes)
if err != nil {
  panic(err)
}
```

In this case you are probably going to see:

```
Failed to instantiate the module:
    compile error: Validation error "Bad magic number" <nil>
```

This will be [because you are compiling a non-main package](https://github.com/golang/go/issues/35657), so you should use `package main` instead of `package hello` when compiling your wasm module.

The next problem you'll run into is that you aren't exporting `Sum` and then you'll need to add a noop `main` function since you are compiling a `main` package, so your module code should ultimately look more like this

```
package main

func main() {}

//go:export sum
func sum(i, j int) int {
	return i + j
}
```

The next problem you'll run into after that will be:

```
Failed to instantiate the module:
    8 link errors: (1 of 8) Import not found, namespace: go, name: debug (2 of 8) Import not found, namespace: go, name: runtime.wasmExit (3 of 8) Import not found, namespace: go, name: runtime.wasmWrite (4 of 8) Import not found, namespace: go, name: runtime.nanotime (5 of 8) Import not found, namespace: go, name: runtime.walltime (6 of 8) Import not found, namespace: go, name: runtime.scheduleTimeoutEvent (7 of 8) Import not found, namespace: go, name: runtime.clearTimeoutEvent (8 of 8) Import not found, namespace: go, name: runtime.getRandomData
```

I'm still trying to understand how to address this problem, but my understanding is that these functions are expected by the golang wasm module to be injected by the runtime in order to effectively interoperate with it.

**Comment by louisliu2048** [comment]
@waynr Got it. Thank u!

**Comment by soulteary** [comment]
@waynr There is a simple solution to the problem of the need to declare exported functions, but you need to use tinygo to compile the wasm program of the standard wasi interface. 

```
Failed to instantiate the module:
    8 link errors: (1 of 8) Import not found, namespace: go, name: debug (2 of 8) Import not found, namespace: go, name: runtime.wasmExit (3 of 8) Import not found, namespace: go, name: runtime.wasmWrite (4 of 8) Import not found, namespace: go, name: runtime.nanotime (5 of 8) Import not found, namespace: go, name: runtime.walltime (6 of 8) Import not found, namespace: go, name: runtime.scheduleTimeoutEvent (7 of 8) Import not found, namespace: go, name: runtime.clearTimeoutEvent (8 of 8) Import not found, namespace: go, name: runtime.getRandomData

```

demo: https://github.com/wasmerio/wasmer-go/pull/315
detail: https://github.com/wasmerio/wasmer-go/issues/275
